service: time-tracker-api

provider:
  name: aws
  runtime: python3.9
  region: eu-west-2
  stage: ${opt:stage, "dev"}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    useDownloadCache: true
    useStaticCache: true
    noDeploy:
      - pytest
    usePoetry: true
    layer:
      name: time-tracker-api-layer
      description: time-tracker-api layer
      compatibleRuntimes:
        - python3.9
        
functions:
  app:
    package:
      include:
        - '!./**'
        - "./app"
      exclude:
        - "**"
    handler: app.main.handler
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: any
          path: /{proxy+}